[build-system]
requires = ["setuptools>=84.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "deproc-utils-tree-sitter"
version = "0.1.1"
description = "Tree Sitter utilities for deproc."
authors = [
    { name = "Gurveer Singh Virk", email = "gurveervirk.15517@gmail.com" }
]
license = {text = "Apache-2.0"}
requires-python = ">=3.10"
dependencies = [
    "tree-sitter>=0.25.2",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries",
]

[project.urls]
Homepage = "https://github.com/gurveervirk/deproc"
Repository = "https://github.com/gurveervirk/deproc"

[tool.setuptools]
py-modules = []

[tool.setuptools.packages.find]
where = ["."]
include = ["deproc.utils*"]
